### ISSUE TITLE
Train with Implicite and Explicite Feedback at the same time

### ISSUE THREAD

**Issue by Tunnelbliick** [ankane/disco-rust#2]
Hello when i initialize the data i have both Implicite and explicite Feedback.

From the small doccumentation im crurently a bit confused how i am supposed to train using both implicite and explicite Feedback

I thought the fit_eval_explicit would be for this but it kinda isnt.

**Comment by ankane** [comment]
Hey @Tunnelbliick, Disco only supports one or the other, not both.
