### ISSUE TITLE
Practical example of Storing Recommendations

### ISSUE THREAD

**Issue by berkes** [ankane/disco-rust#3]
Hi and thanks for the great library!

In the README you say

> Storing Recommendations
> 
> Save recommendations to your database. Alternatively, you can store only the factors and use a library like [pgvector-rust](https://github.com/ankane/pgvector-rust).

And I'd love to help out with making this a bit more concrete.

I've played with the former and that's straightforward. Though I guess an example using sqlite or even writing to a CSV migh clarify this even more. 

The latter is quite vague, though. For one, it's unclear how to extract the vectors from the recommendor. there's `item_factors(item_id)` and `user_factors(user_id)` to extract it; one could loop over all `item_ids()` and `user_ids()` to get the vectors. 
But, once stored, it's unclear how it can be used. Can we "rehydrate" a "pre-trained" `Recommender` from this? Should we now forego the `Recommender` entirely and rely on the pgvector API to get nearest neighbors etc, instead? And if the vectors are stored merely to "cache" (rehydrate a pre-trained) Recommender, is pgvector needed at all or can we use an array-type instead?

I'd gladly contribute a short paragraph or separate .md file in which this is worked out. I want/need to work it out for myself anyway :). But only if this is wanted. And I would love some direction, as it is unclear to me what the common idea and goal should be. Also, I'm new to MF and Vector databases, so please excuse any stupidity from my side.

**Comment by ankane** [comment]
Hi @berkes, added a [full example](https://github.com/pgvector/pgvector-rust/blob/master/examples/disco/src/main.rs). User-based recommendations are the maximum inner product search (`<#>` operator in pgvector) between the factors for the user and all items, and item-based recommendations are the cosine distance (`<=>` operator) between the factors for the item and all other items. Once the factors are stored, the `Recommender` is no longer needed, and you can use any nearest neighbor search library (not just pgvector).

**Comment by berkes** [comment]
Wow, thanks. 
Extracting by looping over the ids and their values makes sense, I suspected as much. Then ditching the recommender and simply using PG makes sense too. 

This helps me move forward a lot. Thanks!

I'm still wondering if there'd be a way to re-hydrate the recommender, when we want to re-calculate, but I'll leave that for another time, when I have time to research my use-case in more depth¹.

I'm closing this issue for now if that's OK?

¹ On the surface the issue is that I receive new ratings over time, and want to re-build the recommendor/user_factors/item_factors ASAP after receiving them. It appears I'll need to re-import and re-fit everything. Which is OK, but I suspect can be sped up by storing & reading the inner state of the recommender someway. But like I said, this is all rather new to me. So I need more to time to research it.
