### ISSUE TITLE
Partial training?

### ISSUE THREAD

**Issue by berkes** [ankane/disco-rust#4]
I'm not very familiar with the mathematics behind matrix factorization, so please forgive me if what I'm asking is silly.
This is more support because of my lack of understanding of the underlying principles. I've tried to research it, but I fail to understand how any potential solutions could apply to discorec.

My use-case is pretty normal:

1. A user has no ratings and rates some items.
2. I retrain the set.
3. I upsert all existing ratings in PG.
4. The user now has ratings.

Step 2 takes about 45 minutes but step 3 is really heavy. A full retrain + upsert takes above 3 hours on my machine and I'm parrallelizing the upsert handling.

I can imagine that step 2 is required always, as the entire matrix must be known before we can factorize it for one user.

But step 3, I think, could be improved. Again: not sure.

As I understand it, the items will now all have new vectors. But do they differ significant?  Could I maybe ignore all updated items-vectors for now, and still get somewhat relevant suggestions?
And when I tested discorec with small and controlled sets, I saw that, somehow, all user-vectors now change too. Why would that be? Is that maybe an artifact of handling/rounding floats? Is there some randomization at play? Or is this fundamentally always so? 
I could imagine that here too, I could just ignore all user-vectors that might've changed and only store the new-users new vectors?

If there's anything I can do help with this too, like write some tests or examples or documentation, please let me know.

**Comment by ankane** [comment]
Hi @berkes, Disco doesn't currently support incremental training. I may try to add this in the future (with [online NMF](https://en.wikipedia.org/wiki/Non-negative_matrix_factorization#Online_NMF) or [another approach](https://stats.stackexchange.com/questions/320962/matrix-factorization-in-recommender-systems-adding-a-new-user)), but you'll probably want to use a different library for now.
